In [9]:
import numpy as np

# Random Seed

In [85]:
np.random.seed(25)
print(np.random.rand(3))

np.random.seed(25)
print(np.random.rand(3))

print(np.random.rand(3))
print(np.random.rand(3))

[0.87012414 0.58227693 0.27883894]
[0.87012414 0.58227693 0.27883894]
[0.18591123 0.41110013 0.11737555]
[0.68496874 0.43761106 0.55622933]


# Reshape

In [122]:
a = np.arange(4)
print(a,'\n')

b = np.reshape(a,(2,2))
print(b, '\n')

c = b.reshape((4,))
print(c)

[0 1 2 3] 

[[0 1]
 [2 3]] 

[0 1 2 3]


# Iter

In [132]:
a = np.arange(4).reshape((2,2))
for i in np.nditer(a):
    print(i)

0
1
2
3


In [162]:
a = np.arange(2,10,2)
print(a)
print(a>5)
b = np.flatnonzero(a>5)
print(b)

[2 4 6 8]
[False False  True  True]
[2 3]
